apiVersion: apps/v1
kind: Deployment

metadata:
  name: devsecops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devsecops-demo

  template:
    metadata:
      labels:
        app: devsecops-demo

    spec:
      containers:
      - name: devsecops-demo
        image: wejdenehm/devsecops-demo:b24649b9904b48ae760cf0dc11dcf6e715d9f23e
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
