apiVersion: apps/v1
kind: Deployment

metadata:
  name: devsecops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devsecops-demo

  template:
    metadata:
      labels:
        app: devsecops-demo

    spec:
      containers:
      - name: devsecops-demo
        image: wejdenehm/devsecops-demo:607bb345ee64ec6800253974039a1c985c4d17f4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
