apiVersion: apps/v1
kind: Deployment

metadata:
  name: devsecops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devsecops-demo

  template:
    metadata:
      labels:
        app: devsecops-demo

    spec:
      containers:
      - name: devsecops-demo
        image: wejdenehm/devsecops-demo:8f6d54e0ec921d0e57617dc0c31ba34eba9123b6
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
