apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "devsecops-demo.fullname" . }}
  labels:
    app: {{ include "devsecops-demo.name" . }}

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "devsecops-demo.name" . }}

  template:

    metadata:
      labels:
        app: {{ include "devsecops-demo.name" . }}

    spec:

      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: 1000


      containers:

      - name: {{ .Chart.Name }}

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}


        env:

        - name: APP_VERSION
          value: {{ .Values.env.APP_VERSION | quote }}

        - name: BUILD_DATE
          value: {{ .Values.env.BUILD_DATE | quote }}

        - name: BUILD_BRANCH
          value: {{ .Values.env.BUILD_BRANCH | quote }}

        - name: BUILD_COMMIT
          value: {{ .Values.env.BUILD_COMMIT | quote }}



        ports:

        - name: http
          containerPort: 5000
          protocol: TCP



        livenessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 15
          periodSeconds: 20



        readinessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 5
          periodSeconds: 10




        securityContext:

          allowPrivilegeEscalation: false

          capabilities:
            drop:
            - ALL

          readOnlyRootFilesystem: false



        resources:

          {{- toYaml .Values.resources | nindent 10 }}
