apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: devsecops-demo-monitor

spec:

  selector:
    matchLabels:
      app: devsecops-demo

  endpoints:

  - port: http
    path: /metrics
    interval: 15s
